package com.supplymind.config.api;

import com.supplymind.foundation.model.MaterialValidationConfigV1;
import com.supplymind.foundation.model.ModelRules;
import com.supplymind.foundation.model.SchemaValidationException;

import java.math.RoundingMode;
import java.util.List;
import java.util.Objects;

/**
 * D8-T01 frozen config-workflow wire contract. Request DTOs are CONTROLLED: the client names
 * the target and its business fields but never configVersion/routeEffectiveAt/supersedesItemId/
 * audit time - those are always generated by the backend activation chain. Capability and
 * history views are read-only projections over existing stores.
 */
public final class ConfigV1 {

    private ConfigV1() {
    }

    /** Read-only projection of the active monitor-series configuration. */
    public record ConfigView(
            String schemaVersion,
            int configVersion,
            String mode,
            String updatedAt,
            List<ItemView> items
    ) {
        public ConfigView {
            items = items == null ? List.of() : List.copyOf(items);
        }
    }

    /** Read-only item projection; wire field names are frozen by the contract test. */
    public record ItemView(
            String itemId,
            String displayName,
            boolean enabled,
            String sourceIntent,
            String providerType,
            String accessMethod,
            String actualSourceName,
            String routeDecision,
            String fallbackReason,
            String routeEffectiveAt,
            String supersedesItemId,
            String externalCode,
            String sourceFieldKey,
            String rateKind,
            String calculationVersion,
            int calculationScale,
            int displayScale,
            String roundingMode,
            String calendarVersion,
            String currency,
            String baseCurrency,
            String unit
    ) {
    }

    /** One immutable config/history snapshot; a manifest failure is reported, never 500. */
    public record HistoryEntry(
            int configVersion,
            boolean verified,
            String message
    ) {
    }

    /** Secret-free provider capability projection (providerType/accessMethod/rateKind support). */
    public record CapabilityView(
            String providerId,
            String providerType,
            String accessMethod,
            String actualSourceName,
            boolean supportsCurrentData,
            boolean supportsHistoryData,
            List<String> supportedItemIds,
            List<String> configuredRateKinds
    ) {
        public CapabilityView {
            supportedItemIds = supportedItemIds == null ? List.of() : List.copyOf(supportedItemIds);
            configuredRateKinds = configuredRateKinds == null ? List.of() : List.copyOf(configuredRateKinds);
        }
    }

    /**
     * Controlled ADD request. The client describes the target business fields only; the backend
     * generates configVersion, routeEffectiveAt and audit time and validates capability.
     */
    public record AddItemRequest(
            String itemId,
            String displayName,
            String sourceIntent,
            String providerType,
            String accessMethod,
            String actualSourceName,
            String routeDecision,
            String fallbackReason,
            String externalCode,
            String sourceFieldKey,
            String rateKind,
            String calculationVersion,
            Integer calculationScale,
            Integer displayScale,
            String roundingMode,
            String calendarVersion,
            String currency,
            String baseCurrency,
            String unit,
            MaterialValidationRequest materialValidation,
            String backfillFrom,
            String backfillTo
    ) {
        public AddItemRequest {
            ModelRules.id(itemId, "itemId");
            ModelRules.nonBlank(displayName, "displayName");
            ModelRules.nonBlank(sourceIntent, "sourceIntent");
            ModelRules.nonBlank(providerType, "providerType");
            ModelRules.nonBlank(accessMethod, "accessMethod");
            ModelRules.nonBlank(actualSourceName, "actualSourceName");
            ModelRules.nonBlank(routeDecision, "routeDecision");
            ModelRules.nonBlank(externalCode, "externalCode");
            ModelRules.nonBlank(rateKind, "rateKind");
            ModelRules.nonBlank(calculationVersion, "calculationVersion");
            Objects.requireNonNull(calculationScale, "calculationScale");
            Objects.requireNonNull(displayScale, "displayScale");
            Objects.requireNonNull(roundingMode, "roundingMode");
            ModelRules.nonBlank(calendarVersion, "calendarVersion");
            ModelRules.nonBlank(currency, "currency");
            ModelRules.nonBlank(unit, "unit");
            if (backfillFrom != null) {
                ModelRules.isoDateText(backfillFrom, "backfillFrom");
            }
            if (backfillTo != null) {
                ModelRules.isoDateText(backfillTo, "backfillTo");
            }
            // M1: a backfill range must be both-or-neither - a one-sided date request is invalid.
            if ((backfillFrom == null) != (backfillTo == null)) {
                throw new SchemaValidationException(
                        "backfillFrom and backfillTo must be provided together (both or neither)");
            }
            if (backfillFrom != null && backfillTo != null && backfillFrom.compareTo(backfillTo) > 0) {
                throw new SchemaValidationException("backfillFrom must not be after backfillTo");
            }
        }
    }

    /** Controlled material validation config (DEC-059); only legal for rateKind=material. */
    public record MaterialValidationRequest(
            String valueMinExclusive,
            String valueMaxInclusive,
            Integer staleThresholdDays,
            String canonicalSpecCode,
            List<String> acceptedSpecAliases
    ) {
        public MaterialValidationRequest {
            acceptedSpecAliases = acceptedSpecAliases == null ? List.of() : List.copyOf(acceptedSpecAliases);
            if (valueMinExclusive == null || valueMinExclusive.isBlank()) {
                throw new SchemaValidationException("materialValidation.valueMinExclusive is required");
            }
            if (staleThresholdDays == null || staleThresholdDays <= 0) {
                throw new SchemaValidationException("materialValidation.staleThresholdDays must be positive");
            }
            if (canonicalSpecCode == null || canonicalSpecCode.isBlank()) {
                throw new SchemaValidationException("materialValidation.canonicalSpecCode is required");
            }
        }

        public MaterialValidationConfigV1 toFrozen() {
            return new MaterialValidationConfigV1(
                    valueMinExclusive, valueMaxInclusive, staleThresholdDays, canonicalSpecCode,
                    acceptedSpecAliases);
        }
    }

    /** REPLACE request: oldItemId is disabled (history preserved), the replacement is added. */
    public record ReplaceItemRequest(
            String oldItemId,
            AddItemRequest newItem
    ) {
        public ReplaceItemRequest {
            ModelRules.id(oldItemId, "oldItemId");
            Objects.requireNonNull(newItem, "newItem");
            if (oldItemId.equals(newItem.itemId())) {
                throw new SchemaValidationException("replacement itemId must differ from the replaced itemId");
            }
        }
    }

    /** Workflow result: the new active config, the CURRENT intake outcome and any backfill job. */
    public record WorkflowResult(
            ConfigView config,
            CurrentIntakeView currentIntake,
            List<BackfillJobView> backfillJobs
    ) {
        public WorkflowResult {
            backfillJobs = backfillJobs == null ? List.of() : List.copyOf(backfillJobs);
        }

        /** Backward-compatible constructor without the current-intake view. */
        public WorkflowResult(ConfigView config, List<BackfillJobView> backfillJobs) {
            this(config, null, backfillJobs);
        }

        /** M1: the combined intake chain used internally by the workflow. */
        public record IntakeChain(
                CurrentIntakeView currentIntake,
                List<BackfillJobView> backfillJobs
        ) {
            public IntakeChain {
                backfillJobs = backfillJobs == null ? List.of() : List.copyOf(backfillJobs);
            }
        }
    }

    /**
     * M1: honest CURRENT-value intake outcome. status is SUCCEEDED / AWAITING_MANUAL_INPUT /
     * FAILED; rawCount and failureReasons carry the real persisted result. Never faked, never a
     * WAITING job - the current acquisition is a distinct semantic entry from history backfill.
     */
    public record CurrentIntakeView(
            String itemId,
            String status,
            int rawCount,
            List<String> failureReasons
    ) {
        public CurrentIntakeView {
            failureReasons = failureReasons == null ? List.of() : List.copyOf(failureReasons);
        }
    }

    /** Read-only backfill job projection. */
    public record BackfillJobView(
            String jobId,
            String itemId,
            String fromDate,
            String toDate,
            String status,
            List<String> completedPeriods,
            String currentCheckpoint,
            List<String> failureReasons,
            int configVersion,
            String createdAt,
            String updatedAt
    ) {
        public BackfillJobView {
            completedPeriods = completedPeriods == null ? List.of() : List.copyOf(completedPeriods);
            failureReasons = failureReasons == null ? List.of() : List.copyOf(failureReasons);
        }
    }

    /** RoundingMode helper: map the frozen rounding mode wire name. */
    public static RoundingMode roundingMode(String name) {
        try {
            return RoundingMode.valueOf(name);
        } catch (IllegalArgumentException exception) {
            throw new SchemaValidationException("roundingMode must be a Java RoundingMode enum string");
        }
    }
}
