package com.supplymind.foundation.storage;

import com.supplymind.foundation.codec.JsonV1Codec;
import com.supplymind.foundation.model.AccessMethod;
import com.supplymind.foundation.model.Mode;
import com.supplymind.foundation.model.MonitorSeriesConfigV1;
import com.supplymind.foundation.model.MonitorSeriesItemV1;
import com.supplymind.foundation.model.ProviderType;
import com.supplymind.foundation.model.RawReceiptV1;
import com.supplymind.foundation.model.RouteDecision;
import com.supplymind.foundation.model.SchemaV1;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Base64;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class RawAndConfigStoreTest {

    private static final OffsetDateTime NOW = OffsetDateTime.parse("2026-08-08T10:00:00+08:00");
    private static final Clock CLOCK = Clock.fixed(Instant.parse("2026-08-08T02:00:00Z"), ZoneOffset.UTC);

    @TempDir
    Path temporaryDirectory;

    @Test
    void configActivationCreatesExactHistoryAndRawIsIdempotentOrProducesConflictEvidence() throws Exception {
        DataRoot root = DataRoot.forTest(temporaryDirectory);
        AtomicMoveSupport.probeOrFail(root);
        AtomicFileStore files = new AtomicFileStore(root, new DirtyMarkerCodec());
        ConfigActivationStore configurations = new ConfigActivationStore(root, files, CLOCK);
        MonitorSeriesConfigV1 configuration = testConfiguration();
        configurations.activate(configuration);

        String historyRef = DataPaths.configHistoryRef(1);
        Path history = root.resolveDataRef(historyRef);
        Path active = root.resolveDataRef(DataPaths.configActiveRef());
        Path historyManifest = root.resolveDataRef(DataPaths.manifestRef(historyRef));
        Path activeManifest = root.resolveDataRef(DataPaths.manifestRef(DataPaths.configActiveRef()));
        assertArrayEquals(Files.readAllBytes(history), Files.readAllBytes(active));
        assertEquals(OffsetDateTime.now(CLOCK), JsonV1Codec.decodeFile(Files.readAllBytes(active),
                        MonitorSeriesConfigV1.class).updatedAt(),
                "persisted config updatedAt must be generated by the server Clock");
        assertTrue(ManifestVerifier.matches(history, historyManifest, List.of()));
        assertTrue(ManifestVerifier.matches(active, activeManifest, List.of()));

        byte[] activeManifestBeforeNoOp = Files.readAllBytes(activeManifest);
        configurations.activate(configuration);
        assertArrayEquals(activeManifestBeforeNoOp, Files.readAllBytes(activeManifest),
                "same configVersion/same bytes must not rewrite a valid manifest");

        RawReceiptStore rawStore = new RawReceiptStore(root, files, CLOCK);
        RawReceiptV1 receipt = rawReceipt("7.123456789000");
        RawReceiptStore.StoredRawReceipt first = rawStore.store(receipt);
        Path raw = root.resolveDataRef(receipt.rawRef());
        Path rawManifest = root.resolveDataRef(DataPaths.manifestRef(receipt.rawRef()));
        assertEquals(receipt.rawRef(), first.rawRef());
        assertTrue(ManifestVerifier.matches(raw, rawManifest, List.of(receipt.runId())));

        byte[] manifestBeforeIdempotentReplay = Files.readAllBytes(rawManifest);
        rawStore.store(receipt);
        assertArrayEquals(manifestBeforeIdempotentReplay, Files.readAllBytes(rawManifest),
                "same raw hash may repair a manifest but must not rewrite an already valid one");

        RawReceiptConflictException conflict = assertThrows(RawReceiptConflictException.class,
                () -> rawStore.store(rawReceipt("7.200000000000")));
        Path conflictEvidence = root.resolveDataRef(conflict.conflictRef());
        assertTrue(Files.isRegularFile(conflictEvidence));
        assertTrue(ManifestVerifier.matches(conflictEvidence,
                root.resolveDataRef(DataPaths.manifestRef(conflict.conflictRef())), List.of(receipt.runId())));
        assertArrayEquals(JsonV1Codec.encodeFile(receipt), Files.readAllBytes(raw),
                "immutable raw must never be overwritten by a collision");
    }

    private static MonitorSeriesConfigV1 testConfiguration() {
        return new MonitorSeriesConfigV1(
                SchemaV1.VERSION,
                1,
                Mode.TEST,
                NOW,
                List.of(new MonitorSeriesItemV1(
                        "FX.TEST.CNY",
                        "test/contract fixture exchange rate",
                        true,
                        "test/contract fixture",
                        ProviderType.SYNTHETIC_DEMO,
                        AccessMethod.SYNTHETIC_DEMO,
                        "test/contract fixture",
                        RouteDecision.SYNTHETIC_DEMO,
                        null,
                        NOW,
                        null,
                        "TEST",
                        "fixture-rate",
                        "test-rate",
                        "arithmetic-mean-v1",
                        12,
                        9,
                        RoundingMode.HALF_UP,
                        "golden-calendar-v1",
                        "CNY",
                        "TEST",
                        "CNY/1 TEST",
                        null
                ))
        );
    }

    private static RawReceiptV1 rawReceipt(String rawValue) {
        byte[] payload = "test/contract fixture complete response bytes".getBytes(StandardCharsets.UTF_8);
        return new RawReceiptV1(
                SchemaV1.VERSION,
                RawReceiptV1.deriveRawRef(Mode.TEST, ProviderType.SYNTHETIC_DEMO, "FX.TEST.CNY", NOW, "raw-test-run-1"),
                "raw-test-acquisition-1",
                "raw-test-run-1",
                Mode.TEST,
                ProviderType.SYNTHETIC_DEMO,
                AccessMethod.SYNTHETIC_DEMO,
                1,
                "test/contract fixture",
                null,
                "test/contract fixture",
                "FX.TEST.CNY",
                "2026-08-08",
                "2026-08-08",
                null,
                null,
                NOW,
                null,
                rawValue,
                "CNY/1 TEST",
                "CNY",
                null,
                null,
                "application/octet-stream",
                "base64",
                Base64.getEncoder().encodeToString(payload),
                JsonV1Codec.sha256LowerHex(payload),
                  "test/contract fixture field",
                  NOW,
                  null,
                  null
          );
    }
}